/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary': '#e4cb9f',
        'background': '#1f0e12',
        'on-primary-fixed': '#241a00',
        'primary-fixed': '#ffe088',
        'on-error': '#690005',
        'tertiary-fixed-dim': '#dbc497',
        'secondary-container': '#896c00',
        'on-tertiary-container': '#534321',
        'primary-container': '#d4af37',
        'on-secondary-container': '#fff3dc',
        'inverse-on-surface': '#402b2f',
        'primary-fixed-dim': '#e9c349',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#554522',
        'surface-container-high': '#392429',
        'tertiary-fixed': '#f9e0b1',
        'secondary-fixed-dim': '#e7c35a',
        'tertiary-container': '#c7b085',
        'inverse-surface': '#fcdae0',
        'outline-variant': '#4d4635',
        'surface-dim': '#1f0e12',
        'secondary': '#e7c35a',
        'surface-bright': '#493338',
        'secondary-fixed': '#ffe08b',
        'on-secondary-fixed': '#241a00',
        'surface-container': '#2d1a1f',
        'surface-container-low': '#29161b',
        'on-primary': '#3c2f00',
        'on-primary-fixed-variant': '#574500',
        'error-container': '#93000a',
        'surface-container-lowest': '#1a090d',
        'error': '#ffb4ab',
        'on-surface-variant': '#d0c5af',
        'surface-container-highest': '#442f34',
        'on-background': '#fcdae0',
        'on-primary-container': '#554300',
        'inverse-primary': '#735c00',
        'surface-tint': '#e9c349',
        'on-surface': '#fcdae0',
        'on-tertiary': '#3d2e0e',
        'primary': '#f2ca50',
        'outline': '#99907c',
        'on-secondary': '#3d2f00',
        'on-tertiary-fixed': '#261a00',
        'surface-variant': '#442f34',
        'on-secondary-fixed-variant': '#584400',
        'surface': '#1f0e12',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-2xl': '5rem',
        'gutter-mobile': '1rem',
        'space-sm': '0.75rem',
        'space-xs': '0.375rem',
        'margin-tablet': '2.5rem',
        'margin': '4rem',
        'space-md': '1.25rem',
        'gutter': '1.5rem',
        'space-xl': '3.5rem',
        'margin-mobile': '1.25rem',
        'space-lg': '2rem',
      },
      fontFamily: {
        'headline-lg': ['"Playfair Display"', 'serif'],
        'label-caps': ['Manrope', 'sans-serif'],
        'headline-xl': ['"Playfair Display"', 'serif'],
        'headline-xl-mobile': ['"Playfair Display"', 'serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'label-md': ['Manrope', 'sans-serif'],
        'display-hero': ['"Playfair Display"', 'serif'],
        'label-sm': ['Manrope', 'sans-serif'],
        'body-sm': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'headline-md': ['"Playfair Display"', 'serif'],
        'headline-sm': ['"Playfair Display"', 'serif'],
        'display-hero-mobile': ['"Playfair Display"', 'serif'],
      },
      fontSize: {
        'headline-lg':        ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'label-caps':         ['11px', { lineHeight: '16px', letterSpacing: '0.18em', fontWeight: '600' }],
        'headline-xl':        ['42px', { lineHeight: '52px', letterSpacing: '-0.015em', fontWeight: '500' }],
        'headline-xl-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg':            ['18px', { lineHeight: '30px', fontWeight: '300' }],
        'label-md':           ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'display-hero':       ['56px', { lineHeight: '68px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'label-sm':           ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'body-sm':            ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md':            ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md':        ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm':        ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-hero-mobile':['38px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
